isso:
  image: wonderfall/isso
  environment:
    - GID=1000
    - UID=1000
  volumes:
    - /home/seba/web/nomadblog.de/static/cfg:/config
    - /home/seba/web/nomadblog.de/static/db:/db
  ports:
    - "127.0.0.1:80:8080"
