title = "no mad blog"
languageCode = "en-us"
baseurl = "https://nomadblog.de/"
pluralizeListTitles = false
PygmentsCodeFences = true
pygmentsuseclasses = true
ignoreFiles = [ "/css/.sass-cache" ]
theme = "nomadblog"

[Taxonomies]
tag = "tags"

[params]
email = "sebastian@nomadblog.de"