#!/bin/bash
if (( $# < 1));
then
	echo "commit message required"
	exit
fi
hugo
rsync -arv --delete --exclude=db/ --exclude=docker-local/ public/ seba@server:~/web/nomadblog.de
git add .
git commit -m "$1"
git push
